# ======================================================================================================================
#                                                   APP CONFIGURATION
# ======================================================================================================================
# These configuration values are set to match my local environment an personal tuning. In the future this file may
# be .gitignored.

# Needed to avoid the rewriting of these settings after parsing .secrets.toml
dynaconf_merge = true

# Database connection
[database_connection]

# Only for ODBC connections.
# Unicode driver must be used to store Unicode characters in the database. For example: MySQL ODBC 8.0 Unicode Driver.
driver = "MySQL ODBC 8.0 Unicode Driver"

# Connection chain values.
server = "localhost"
database = "NewsAggregatorBackend"

# Only for ODBC connections.
charset = "utf8mb4"

