# ======================================================================================================================
#                                                   APP CONFIGURATION
# ======================================================================================================================
# These configuration values are set to match my local environment an personal tuning. In the future this file may
# be .gitignored.

# Needed to avoid the rewriting of these settings after parsing .secrets.toml.
dynaconf_merge = true

# =========================================================
# == Configuration settings that are not tied to a table ==
# =========================================================
# Execution mode. This value should be overwritten by a environment variable, which has more priority than this setting.
# Set it as <envvar_prefix>_EXECUTION_MODE=<VALUE>, for example: NEWS_AGGR_EXECUTION_MODE=PRODUCTION
# Supported values: "DEVELOPMENT", "PRODUCTION"
execution_mode = "DEVELOPMENT"

# Delay, in minutes, required to fetch the news from a RSS site. If a news reload is requested too soon, it will be
# ignored.
rss_cache_minutes = 30

# ================================================
# == Configuration settings organized in tables ==
# ================================================
# Database connection.
[database_connection]

# Only for ODBC connections.
# Unicode driver must be used to store Unicode characters in the database. For example: MySQL ODBC 8.0 Unicode Driver.
driver = "MySQL ODBC 8.0 Unicode Driver"

# Connection chain values.
server = "localhost"
database = "NewsAggregatorBackend"

# Only for ODBC connections.
charset = "utf8mb4"

# Background session expiration task.
[background_session_expiration]

# Periodic session expiration task delay between calls (in seconds).
task_delay = 60
